### ISSUE TITLE
What does parameter division mean? And how to choose the optimal one?

### ISSUE THREAD

**Issue by lx-1234** [jellevos/private-logic-and-mpso#1]
Hi, Dr. Jelle Vos. I read your paper and test the code recently. I have some confusions about the meaning of parameter `division` in `exact-set-union`. Is it the number of divisions D in the paper? If so, how can I compute an optimal value to minimize the run time?
Thanks in advance.

**Comment by jellevos** [comment]
Hi! I am not a Dr. yet but happy to help you out :)
You are completely right that D is the number of divisions in the paper. The optimal value to minimize run time depends on some real-world characteristics: e.g. the speed of the computer, and the latency and throughput of the network.

If computation is the bottleneck, then choosing D = 2 (or D=3, just any integer close to e) is almost always the fastest. You can check out Appendix D for the details of this.

Realistically, though, you would choose a higher D to reduce the number of interactions (as each interaction requires communication). You would use Equation 24 for this. If you want, I can include a small Python script for this purpose.

**Comment by lx-1234** [comment]
Great, thanks for your help ;)
I read Appendix D carefully and now I get it. And your insights on the real-world characteristics affecting the run time are very helpful.
I don't need the Python script at the moment. Thank you again for taking the time to respond to my question.

**Comment by lx-1234** [comment]
Sorry to bother you again. I tried to write a python script to compute the expected number of ORs. But I am confused by the equation (22) in your paper. 
<img width="407" alt="1684164245816" src="https://github.com/jellevos/private-logic-and-mpso/assets/57345317/89919bad-7823-43ed-b25c-407fc7be7de1">
When log_D^N is a integer, the denominator will be zero. How to understand this equation? Thanks in advance.

**Comment by jellevos** [comment]
You are right that that is the case, this is an oversight on my side. In the case where $D^\left\lceil \log_D N \right\rceil$ is an integer, then the number of partitions in the final round $B = 0$ (in other words, the round before that is the actual last round).

**Comment by lx-1234** [comment]
Yes, i got it. Thank you again!
